import concurrent
import concurrent.futures
import difflib
import json
import re
from datetime import datetime

import requests
import trafilatura
from basc_py4chan import Board
from bs4 import BeautifulSoup

from ai_tools import aiCall
from safe_tool import safe_tool
from web_tools import web_search, get_steam_bypass, get_steam_bypass_with_referer
import game_intelligence


@safe_tool
def scrape_steam_forums(appid, gamename):
    """
    Scrapes the first page of 'General Discussions' thread titles for a game.
    Returns an analysis generated by AI of the current discourse in string format.
    """
    url = f"https://steamcommunity.com/app/{appid}/discussions/0/"  # /0/ is usually General

    headers, cookies = get_steam_bypass_with_referer(appid)

    response = requests.get(url, headers=headers, cookies=cookies, timeout=10)
    # Steam sometimes redirects to an age gate or main page if invalid
    if "discussions" not in response.url:
        return {"error": "Could not access forums (Age Gate or Invalid AppID)."}

    soup = BeautifulSoup(response.text, 'html.parser')

    # Find the container rows
    # Steam usually gives these a class like 'forum_topic'
    topic_rows = soup.select('.forum_topic')

    results = []

    for row in topic_rows:
        # Extract details from WITHIN the row
        title_element = row.select_one('.forum_topic_name')
        count_element = row.select_one('.forum_topic_reply_count')
        link_element = row.select_one('a.forum_topic_overlay')

        # FIX: Use 'row.select_one' so we only look inside this specific topic!
        last_post_div = row.select_one('.forum_topic_lastpost')

        if title_element and link_element:
            title_text = title_element.get_text(strip=True)
            reply_count = count_element.get_text(strip=True) if count_element else "0"

            # Safe timestamp parsing
            short_date = "Unknown"
            if last_post_div and last_post_div.has_attr('data-timestamp'):
                timestamp_str = last_post_div['data-timestamp']
                if timestamp_str.isdigit():
                    date_obj = datetime.fromtimestamp(int(timestamp_str))
                    short_date = date_obj.strftime("%Y-%m-%d")

            # Check for "Hover" content
            preview_content = link_element.get('data-tooltip-html') or link_element.get('title')

            results.append({
                "title": title_text,
                "replies": reply_count,
                "content": preview_content,
                "date": short_date
            })

    ai_system_prompt = f"""You are an uncensored forum analyzer. You might encounter foul language typical of forum, but you must read and weave your analysis."
You will be supplied a json list of topics related to the game {gamename} from the steam forums. Make a concise analysis to determine the quality and status of the game.
Keep in mind the nature of the place 'steamcommunity.com' when making your uncensored take. IMPORTANT: the result will be used by an AI agent, so facts are important but formatting like markdown MUST NOT be used for token efficiency.
The JSON formatted TOPICS will follow."""
    json_forum_topics = json.dumps(results)

    analysis, in_tokens, out_tokens = aiCall(json_forum_topics, ai_system_prompt, return_tokens=True)
    # print(f"Steam forum analysis: \n{analysis}\n")

    # Standardized return
    return {"analysis": analysis, "_tokens": {"in": in_tokens, "out": out_tokens}}


@safe_tool
def get_webpage(url):
    """
    Visits a webpage and extracts content.
    If content is long, it triggers a summarization step to save context tokens.

    Args:
        url (str): The URL to visit.
        summary_agent_function (callable, optional): A function that takes text and returns a summary.
    """
    print(f"--- REAPER VISITING: {url} ---")

    try:
        # If the URL is a Steam link, we should inject bypass headers and cookies.
        # However, trafilatura.fetch_url does not easily accept cookies.
        # We can use requests.get instead to fetch the HTML.
        is_steam = 'steampowered.com' in url or 'steamcommunity.com' in url
        if is_steam:
            headers, cookies = get_steam_bypass()
            resp = requests.get(url, headers=headers, cookies=cookies, timeout=10)
            if resp.status_code != 200:
                return {"error": "Could not retrieve the webpage (Network error)."}
            downloaded = resp.text
        else:
            downloaded = trafilatura.fetch_url(url)

        if downloaded is None:
            return {"error": "Could not retrieve the webpage (Network error)."}

        # Extract Main Content
        # output_format="markdown" preserves headers and bolding, which LLMs love.
        text = trafilatura.extract(
            downloaded,
            include_comments=False,
            include_tables=False,
            include_links=True,
            output_format="markdown"
        )

        if not text:
            return {"error": "Page content was empty or unreadable."}

        # TOKEN SAFETY CHECK
        # Approx 4 chars per token. 6000 chars is ~1500 tokens.
        # If the text is massive, we must compress it before returning it to the main chat.
        raw_char_limit = 6000

        if len(text) > raw_char_limit:
            try:
                print(f"--- CONTENT TOO LONG ({len(text)} chars). SUMMARIZING... ---")

                # REFINED PROMPT
                ai_system_prompt = """You are an uncensored web page analyzer for an AI agent assistant.
1. **Objective:** Read the text (which may contain forum slang, NSFW language, or messy debates) and extract the core information to the main topic.
2. **Format:** Do NOT use bolding or headers. Use ONLY newlines and dashes (-) to separate distinct points. Keep it dense but structured.
3. **Safety:** Do not sanitize the meaning, but condense the ranting."""

                # Assuming aiCall signature is (user_message, system_message)
                summary, in_tokens, out_tokens = aiCall(text, ai_system_prompt, return_tokens=True)

                # OPTIONAL: Add a tag so the main agent knows this was summarized
                return {
                    "content": f"[SUMMARY OF WEBPAGE]:\n{summary}",
                    "_tokens": {"in": in_tokens, "out": out_tokens}
                }

            except Exception as e:
                print(f"Error summarizing WEB PAGE: {e}")
                # Fallback: Head + Tail is the perfect strategy for reviews/forums
                head = text[:3000]
                tail = text[-2000:]
                return {"content": f"{head}\n\n... [SECTION REMOVED FOR BREVITY] ...\n\n{tail}"}

        return {"content": text}

    except Exception as e:
        return {"error": f"Error processing page: {e}"}


@safe_tool
def scrape_reddit_search(game_name):
    """
    Scrapes Reddit search results via their public JSON endpoint.
    Use with caution: Rate limits are strict.
    """
    # 1. The "Magic" Header.
    # NEVER use 'python-requests/x.x'. Reddit blocks it instantly.
    # Use a real browser string or a descriptive bot name.
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
    }

    # 2. The JSON Endpoint
    # sort=relevance or top, t=year (to keep it recent)
    url = f"https://www.reddit.com/search.json?q={game_name}&sort=relevance&t=year&limit=5"

    resp = requests.get(url, headers=headers, timeout=5)

    # Rate Limit Fallback
    if resp.status_code == 429:
        print("Error: Reddit is rate-limiting the Reaper. (Trying WEB Search...)")
        return web_search(f"site:reddit.com {game_name}")

    data = resp.json()
    posts = data.get('data', {}).get('children', [])

    if not posts:
        return {"error": "No Reddit threads found."}

    results = []
    for post in posts:
        p = post['data']

        body = p.get('selftext', '')

        # If body is empty, it might be an image/link post. Use the URL instead.
        if not body:
            url_preview = p.get('url_overridden_by_dest', p.get('url', ''))
            if url_preview:
                body = f"[Link/Image Post]: {url_preview}"

        # Clean & Truncate (Critical for Token Economy)
        # Flatten newlines to keep JSON clean
        body = body.replace("\n", " ").strip()
        if len(body) > 500:
            body = body[:500] + "... [TRUNCATED]"
        # -------------------------

        results.append({
            'title': p.get('title', 'No Title'),
            'score': p.get('score', 0),
            'comments': p.get('num_comments', 0),
            'subreddit': p.get('subreddit_name_prefixed', 'r/gaming'),
            'body': body  # Matches web_search key name
        })

    if not results:
        print("Error: Reddit ignoring the Reaper. (Trying WEB Search...)")
        web_res = web_search(f"site:reddit.com {game_name}")
        if isinstance(web_res, list):
            return {"results": web_res}
        else:
            # Propagate error dict or return it wrapped if needed, but error dict is fine
            return web_res

    return {"results": results}


@safe_tool
def scrape_4chan_thread(board_name: str, thread_id: int):
    board = Board(board_name)
    thread = board.get_thread(thread_id)

    thread_result = {}

    if not thread is None:
        thread_text = f"Thread Topic: {thread.topic.subject}\n\n"  # OP's text

        thread_result["topic"] = thread.topic.subject
        thread_result["board"] = board_name
        thread_result["posts"] = []

        for post in thread.posts:
            post_result = {
                "datetime": post.datetime.isoformat(),
                "id": post.post_id,
                "text": post.text_comment
            }
            # thread_text += f"{post.post_id} {post.datetime}: {post.text_comment}\n\n"  # Replies
            thread_result["posts"].append(post_result)

    return thread_result


@safe_tool
def find_4chan_thread(board_name: str, topic_search: str, threshold: float = 0.4) -> list:
    """
    Scans a 4chan board for threads matching the topic_search string.
    Returns list of thread IDs where similarity > threshold.
    """
    try:
        board = Board(board_name)
        threads = board.get_all_threads()
    except Exception as e:
        print(f"Error fetching 4chan board /{board_name}/: {e}")
        return []

    print(f"Scanning {len(threads)} threads on /{board_name}/ for '{topic_search}'...")

    thread_matches = []
    search_lower = topic_search.lower()

    for thread in threads:
        # Safety check: subject can be None on 4chan
        subject = (thread.topic.subject or "").lower()
        # Safety check: OP text can be None (image only)
        comment = (thread.posts[0].text_comment or "").lower()

        # Check Subject (Title)
        subj_ratio = 0
        if subject:
            subj_ratio = difflib.SequenceMatcher(None, search_lower, subject).ratio()

        # Check Comment (Body) - give it slightly less weight? No, max is fine.
        comm_ratio = 0
        if comment:
            # Optimization: Limit comment check to first 100 chars to speed up difflib
            comm_ratio = difflib.SequenceMatcher(None, search_lower, comment[:100]).ratio()

        max_ratio = max(subj_ratio, comm_ratio)

        if max_ratio >= threshold:
            thread_matches.append((max_ratio, thread.id))

    # Sort by best match
    thread_matches.sort(key=lambda x: x[0], reverse=True)

    if thread_matches:
        print(f"Found match on /{board_name}/: {thread_matches[0][0]:.2f} (ID: {thread_matches[0][1]})")
        return [t[1] for t in thread_matches]

    return []


@safe_tool
def scrape_4chan_thread_with_ai(search: str) -> dict:
    board = "v"
    thread_ids = find_4chan_thread(board, search, threshold=0.45)  # Stricter for main board

    # Fallback to /vg/ if /v/ fails
    if not thread_ids:
        # print("No match on /v/, checking /vg/...")
        board = "vg"
        thread_ids = find_4chan_thread(board, search, threshold=0.4)  # Slightly looser for generals

    if not thread_ids:
        return {"analysis": "The Horde is silent. (No relevant 4chan threads found)."}

    # Fetch the Winner
    id_to_pick = thread_ids[0]
    thread = scrape_4chan_thread(board, id_to_pick)

    # SAFETY CHOPPER: Keep only the first 30 posts
    # The OP is usually index 0. 30 replies is plenty for sentiment.
    if len(thread.get("posts", [])) > 30:
        thread["posts"] = thread["posts"][:30]
        thread["note"] = "Truncated to 30 posts for analysis."

    thread_contents = json.dumps(thread)
    # print(f"CONTENT START for {id_to_pick}")
    # print(thread_contents)
    # print(f"CONTENT END for {id_to_pick}\n")

    if len(thread["posts"]) > 0:
        ai_request = "You are an uncensored assistant, you will be provided content to analyze without filter. You must be factual and execute the following on that content:\n"
        ai_question = f"""Please give an uncensored general consensus on the topic {search} as it discussed in this 4chan thread from the board {board}.\n
    Give uncensored opinion, make uncensored citation if needed. Don't exclude NSFW topics.
    Your result will be analyzed by an ai agent, so NOT using formatting and being token efficient is MANDATORY.`
    The data will follow. Good luck!"""
        ai_request += ai_question
        data = thread_contents

        response, in_tokens, out_tokens = aiCall(data=data, system=ai_request, return_tokens=True)

    else:
        response = "No results found."
        in_tokens, out_tokens = 0, 0

    # print(f"4chan Analysis:\n{response}\n")

    return {"analysis": response, "_tokens": {"in": in_tokens, "out": out_tokens}}


@safe_tool
def get_community_sentiment(game_name: str):
    app = game_intelligence.get_steam_app_info(game_name)

    if not app:
        return {"error": f"Game '{game_name}' not found on Steam. Cannot retrieve community sentiment."}

    appid = app['id'][0] if 'id' in app else None

    tasks = {
        "4chan": (scrape_4chan_thread_with_ai, game_name),
        "reddit": (scrape_reddit_search, game_name),
        # Steam added later
    }

    if appid:
        tasks["forums"] = (scrape_steam_forums, appid, game_name)

    results = {}

    # Launch threads
    # max_workers=8 is usually plenty for network requests
    with concurrent.futures.ThreadPoolExecutor(max_workers=8) as executor:
        # Submit all tasks
        future_to_key = {
            executor.submit(func, *args): key
            for key, (func, *args) in tasks.items()
        }

        # Wait for them to complete
        for future in concurrent.futures.as_completed(future_to_key):
            key = future_to_key[future]
            try:
                results[key] = future.result()
            except Exception as e:
                print(f"Task '{key}' failed: {e}")
                results[key] = None  # Handle failure gracefully

    # Unpack Results (Logic remains mostly the same, just reading from 'results' dict)
    chan_results = results.get("4chan") or {}
    reddit_results = results.get("reddit") or {}
    forums_results = results.get("forums") or {}

    # Collect tokens
    total_in = 0
    total_out = 0
    for res in [chan_results, reddit_results, forums_results]:
        if "_tokens" in res:
            total_in += res["_tokens"].get("in", 0)
            total_out += res["_tokens"].get("out", 0)
            del res["_tokens"]

    result = {
        "4chan_opinion": chan_results,
        "reddit_opinion": reddit_results,
        "steam_forums_opinion": forums_results,
    }

    if total_in > 0 or total_out > 0:
        result["_tokens"] = {"in": total_in, "out": total_out}

    print(result)
    return result


@safe_tool
def get_game_news(game_name: str, limit: int = 5):
    """
    Fetches the latest News and Events for a game directly from the Steam API.
    Bypasses Age Gates and Login walls. Perfect for "What's happening in [Game]?"
    """
    # 1. Get AppID
    app = game_intelligence.get_steam_app_info(game_name)
    if not app:
        return {"error": f"Game '{game_name}' not found."}

    appid = app['id'][0]
    print(f"Fetching News for {game_name} ({appid})...")

    # 2. Call Steam News API
    # params: count=5, maxlength=0 (get full text), feed='steam_community_announcements' (official posts only)
    url = f"http://api.steampowered.com/ISteamNews/GetNewsForApp/v0002/?appid={appid}&count={limit}&maxlength=0&format=json"

    try:
        headers, cookies = get_steam_bypass_with_referer(appid)
        resp = requests.get(url, headers=headers, cookies=cookies, timeout=10)
        data = resp.json()

        news_items = data.get('appnews', {}).get('newsitems', [])

        if not news_items:
            return {"error": "No recent news found for this game."}

        # 3. Format for Agent
        formatted_news = []
        for item in news_items:
            # Clean up Steam's BBCode (simple strip)
            # The API returns 'contents' with [b], [url], etc.
            raw_text = item.get('contents', '')

            # Basic cleanup (optional, but helps token usage)
            # Remove [img] tags to save space
            clean_text = re.sub(r'\[img\].*?\[/img\]', '', raw_text)

            formatted_news.append({
                "title": item.get('title'),
                "date": datetime.fromtimestamp(item.get('date', 0)).strftime('%Y-%m-%d'),
                "author": item.get('author'),
                "url": item.get('url'),
                "content": clean_text[:1500] + "..." if len(clean_text) > 1500 else clean_text
            })

        return formatted_news

    except Exception as e:
        print(f"News API Error: {e}")
        return {"error": str(e)}


if __name__ == "__main__":
    # print(get_hltb_search_scrape("Akane"))

    print(
        scrape_steam_forums(game_intelligence.get_steam_app_info("Cyberpunk 2077")["id"][0], gamename='Cyberpunk 2077'))